<a href="https://colab.research.google.com/github/tejartejarte/project/blob/main/Classification_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
                                                                      ####Classification####

In [3]:
#####1)SVM

In [4]:
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
svm=pd.read_csv("/content/Data (2).csv")

In [ ]:
svm.info()

In [27]:
svm.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [ ]:
X=svm.iloc[:,:-1].values
Y=svm.iloc[:,-1].values

In [ ]:
X

In [ ]:
Y

In [ ]:
#Spliting the dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [ ]:
print(X_train)

In [ ]:
print(Y_train)

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)


In [ ]:
X_train

In [ ]:
X_test

In [ ]:
#importing the model
from sklearn.svm import SVC
classifier=SVC(kernel="linear",random_state=0)
classifier.fit(X_train,Y_train)

In [ ]:
Y_pred=classifier.predict(X_test)

In [ ]:
Y_pred

In [ ]:
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

In [ ]:
from sklearn.metrics import confusion_matrix,r2_score,accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
print(cm)

In [ ]:
r2=r2_score(Y_test,Y_pred)
r2

In [ ]:
ac=accuracy_score(Y_test,Y_pred)
ac

In [ ]:
#Visualisingg the training set result
from matplotlib.colors import ListedColormap
X_set,Y_set=scaler.inverse_transform(X_train),Y_train
X1,X2=np.meshgrid(np.arange(start=X_set[:,0].min()-10,stop=X_test[:,0].max()+10,step=0.25),
                     np.arange(start=X_set[:,1].min()-1000,stop=X_set[:,1].max()+1000,step=0.25))
plt.contourf(X1,X2,classifier.predict(scaler.transform(np.array([X1.ravel(),X2.ravel()]).T)).reshape(X1.shape),
             alpha=0.75,cmap=ListedColormap(("red","green")))
plt.xlim(X1.min(),X2.max())
plt.ylim(X2.min(),X2.max())
for i,j in enumerate(np.unique(y_set)):
  plt.scatter(X_set[y_set==j,0],X_set[y_set==j,1],c=ListedColormap(("red","green"))(i),label=j)
plt.title("SVM--Training Set")
plt.xlabel("traing")
plt.ylabel("testing")
plt.legend()
plt.show()

In [ ]:
###2)Kernel SVM
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#import the dataset
ksvm=pd.read_csv("/content/Data (2).csv")

In [ ]:
ksvm.info()

In [ ]:
ksvm.isnull().sum()

In [ ]:
X=ksvm.iloc[:,:-1].values
Y=ksvm.iloc[:,-1].values

In [ ]:
##Splitting the dataset into train set and test set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
#feature Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
#Model
from sklearn.svm import SVC
classifier=SVC(kernel="rbf",random_state=0)
classifier.fit(X_train,Y_train)

In [ ]:
#prediction
Y_pred=classifier.predict(X_test)
Y_pred

In [ ]:
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

In [ ]:
from sklearn.metrics import confusion_matrix,r2_score,top_k_accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
print(cm)

In [ ]:
r2=r2_score(Y_pred,Y_test)
r2

In [ ]:
acc=accuracy_score(Y_test,Y_pred)
acc

In [ ]:
####3)Navie Bayes

In [ ]:
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#import the dataset
nb=pd.read_csv("/content/Data (2).csv")

In [ ]:
nb.info()

In [ ]:
nb.isnull().sum()

In [ ]:
nb.describe()

In [ ]:
X=nb.iloc[:,:-1].values
Y=nb.iloc[:,-1].values

In [ ]:
#Spliting the dataset into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
#Importing the model
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,Y_train)

In [ ]:
#Predicting the test set result
Y_pred=classifier.predict(X_test)
Y_pred

In [ ]:
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

In [ ]:
from sklearn.metrics import confusion_matrix,r2_score,accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
cm

In [ ]:
print(r2_score(Y_test,Y_pred))

In [ ]:
print(accuracy_score(Y_test,Y_pred))

In [ ]:
####4)Decision Tree

In [ ]:
#importing library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#importing the dataset
dt=pd.read_csv("/content/Data (2).csv")

In [ ]:
dt.info()

In [ ]:
dt.isnull().sum()

In [ ]:
X=dt.iloc[:,:-1].values
Y=dt.iloc[:,-1].values

In [ ]:
X

In [ ]:
#traing the dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
#importing the model
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion="entropy",random_state=0)
classifier.fit(X_train,Y_train)

In [ ]:
#Prediction
Y_pred=classifier.predict(X_test)
Y_pred

In [ ]:
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

In [ ]:
#Predicting the model performance
from sklearn.metrics import confusion_matrix,r2_score,top_k_accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
cm

In [ ]:
print(accuracy_score(Y_test,Y_pred))

In [ ]:
print(r2_score(Y_test,Y_pred))

In [ ]:
####5)Random Forest classifier

In [ ]:
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#importing the dataset
rf=pd.read_csv("/content/Data (2).csv")

In [ ]:
rf.info()

In [ ]:
rf.isnull().sum()

In [ ]:
X=rf.iloc[:,:-1].values
Y=rf.iloc[:,-1].values

In [ ]:
X

In [ ]:
Y

In [ ]:
#train and test the model
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
#Model importing
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10,criterion="entropy",random_state=0)
classifier.fit(X_train,Y_train)

In [ ]:
#Predictin the model
Y_pred=classifier.predict(X_test)
Y_pred

In [ ]:
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

In [ ]:
from sklearn.metrics import confusion_matrix,r2_score,accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
cm

In [ ]:
print(r2_score(Y_test,Y_pred))

In [ ]:
print(accuracy_score(Y_test,Y_pred))

In [ ]:
####6)KNN

In [ ]:
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
kn=pd.read_csv("/content/Data (2).csv")

In [ ]:
kn.info()

In [ ]:
kn.isnull().sum()

In [ ]:
X=kn.iloc[:,:-1].values
Y=kn.iloc[:,-1].values

In [ ]:
X

In [ ]:
Y

In [ ]:
#Training the model
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [ ]:
#importing the model
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)
classifier.fit(X_train,Y_train)

In [ ]:
#Prediction
Y_pred=classifier.predict(X_test)
Y_pred

In [ ]:
from sklearn.metrics import accuracy_score,r2_score,confusion_matrix
print(confusion_matrix(Y_test,Y_pred))

In [ ]:
print(accuracy_score(Y_test,Y_pred))

In [ ]:
print(r2_score(Y_test,Y_pred))

In [ ]:
####7)Logistic Regression

In [5]:
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
lr=pd.read_csv("/content/Data (2).csv")

In [7]:
lr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [8]:
lr.isnull().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [9]:
X=lr.iloc[:,:-1].values
Y=lr.iloc[:,-1].values

In [10]:
X

array([[1000025,       5,       1, ...,       3,       1,       1],
       [1002945,       5,       4, ...,       3,       2,       1],
       [1015425,       3,       1, ...,       3,       1,       1],
       ...,
       [ 888820,       5,      10, ...,       8,      10,       2],
       [ 897471,       4,       8, ...,      10,       6,       1],
       [ 897471,       4,       8, ...,      10,       4,       1]])

In [11]:
Y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 4, 4, 4, 4, 2,
       4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 4,
       4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 2, 4,
       4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2,
       2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2,
       2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 4, 2,
       4, 4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 2,
       4, 4, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 2,
       2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4,

In [12]:
#Training the model
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [20]:
X_train

array([[ 752904,      10,       1, ...,       5,       4,       1],
       [1218860,       1,       1, ...,       3,       1,       1],
       [ 411453,       5,       1, ...,       3,       1,       1],
       ...,
       [1214092,       1,       1, ...,       1,       1,       1],
       [1303489,       3,       1, ...,       2,       1,       1],
       [ 378275,      10,       9, ...,       7,       7,       1]])

In [13]:
Y_train

array([4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 4, 4, 2,
       4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 4,
       4, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2,
       2, 4, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 2, 4,
       4, 2, 4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2,
       2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2,
       2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 2, 4, 2, 4, 4, 4, 2,
       2, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 4, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 4, 4,
       4, 2, 2, 4, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 4, 4, 2, 2,

In [14]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [15]:
X_train

array([[-0.49838781,  1.98839518, -0.69781134, ...,  0.61907387,
         0.34532102, -0.33863738],
       [ 0.19242611, -1.22468404, -0.69781134, ..., -0.18860673,
        -0.62157783, -0.33863738],
       [-1.00461394,  0.20335117, -0.69781134, ..., -0.18860673,
        -0.62157783, -0.33863738],
       ...,
       [ 0.1853572 , -1.22468404, -0.69781134, ..., -0.99628733,
        -0.62157783, -0.33863738],
       [ 0.3178948 , -0.51066644, -0.69781134, ..., -0.59244703,
        -0.62157783, -0.33863738],
       [-1.05380275,  1.98839518,  1.90512627, ...,  1.42675446,
         1.31221987, -0.33863738]])

In [16]:
X_test

array([[ 0.45808465, -1.20834278, -0.72017241, ..., -1.01206688,
        -0.57972754, -0.39273091],
       [ 0.40365013, -0.51569441, -0.72017241, ..., -0.58280012,
        -0.57972754, -0.39273091],
       [-1.00854099,  0.17695396,  0.60417149, ...,  0.27573339,
         0.12940347, -0.39273091],
       ...,
       [-2.06664071, -0.16937022, -0.72017241, ..., -1.01206688,
        -0.57972754, -0.39273091],
       [ 0.89776358, -0.16937022,  2.25960136, ...,  2.42206718,
         2.611362  , -0.39273091],
       [ 0.34122161, -0.86201859, -0.72017241, ..., -0.58280012,
        -0.57972754, -0.39273091]])

In [17]:
#import the model
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,Y_train)

LogisticRegression(random_state=0)

In [18]:
#Prediction
Y_pred=classifier.predict(X_test)
Y_pred

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2])

In [19]:
from sklearn.metrics import  confusion_matrix,r2_score,accuracy_score
print(confusion_matrix(Y_pred,Y_test))

[[84  3]
 [ 3 47]]


In [20]:
print(r2_score(Y_pred,Y_test))

0.8110344827586207


In [21]:
print(accuracy_score(Y_pred,Y_test))

0.9562043795620438
